### PR TITLE
FORMS-822: Ability to view last modified date in submissions screen

### PR DESCRIPTION
**Pull request by bcvesalink**
# Description
As a CHEFS Form Reviewer, I need to be able to view the “Last Modified” timestamp and “Last Modified By” username from within the Submission screen so that I can quickly tell whether a form has been modified.
Received from MoH PCD BI Project Team via Fider: [Ability to view last modified date in submissions screen · Common Hosted Form Service Feedback](https://chefs-fider.apps.silver.devops.gov.bc.ca/posts/98/ability-to-view-last-modified-date-in-submissions-screen)

## Types of changes

New feature (non-breaking change which adds functionality) 

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have checked that unit tests pass locally with my changes
- [ ] I have run the npm script lint on the frontend and backend
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have approval from the product owner for the contribution in this pull request

### CODE REVIEW

**Comment by WalterMoar** [comment]
When a new submission is created and it has not yet been modified, it's showing the submission date as the modified date, but with no modified user. Would it be better if the modified date didn't appear until after it was modified?
image

**Comment by WalterMoar** [comment]
Would it be possible to update the modified information on the submission view page _without_ re-opening the page? What I mean is that if I view a submission and edit it, the "header" info isn't immediately updated.
image

**Comment by bcvesalink** [comment]
> When a new submission is created and it has not yet been modified, it's showing the submission date as the modified date, but with no modified user. Would it be better if the modified date didn't appear until after it was modified? 

addressed

**Comment by bcvesalink** [comment]
> Would it be possible to update the modified information on the submission view page _without_ re-opening the page? What I mean is that if I view a submission and edit it, the "header" info isn't immediately updated.

addressed

**Review by WalterMoar — APPROVED** [review]

**Pull request merged**
