### PR TITLE
Submission Edit (Staff)

### PR DESCRIPTION
**Pull request by loneil**
# Description
Staff side edit and audit history functionality. Need "status workflow" enabled on the form for it to show.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2032

Also add in 403 responses to spec
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2052

## Types of changes

New feature (non-breaking change which adds functionality)
Documentation (non-breaking change with enhancements to documentation)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

See migration script for audit history details. Added a submission audit history table and a trigger on the submission table to auto-update this.

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-164

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-164

**Review by jujaga — APPROVED** [review]

**Comment by TimCsaky** [comment]
i guess if the original submitter goes back to view their submission via link in email, the success page shows the latest version of submission by default (potentially updated version).. which could be a good thing

**Comment by loneil** [comment]
> i guess if the original submitter goes back to view their submission via link in email, the success page shows the latest version of submission by default (potentially updated version).. which could be a good thing

**Review by TimCsaky — APPROVED** [review]

**Pull request merged**
