### PR TITLE
About page content update

### PR DESCRIPTION
**Pull request by TimCsaky**
# Description

ticket : https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2427
new content: https://apps.nrs.gov.bc.ca/int/confluence/pages/viewpage.action?pageId=109189105

..tidy up the CHEFS about page.
- remove those two smaller videos that were out of date
- provide more informative wording at top of page
- updated a couple of broken links to the wiki

## Types of changes

Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-279

**Comment by jujaga** [comment]
> Sign in links seem to be breaking
It may have been an SSO anomaly. Login flow appears nominal on the PR atm.

**Review by loneil — APPROVED** [review]
Login seems fine now, not sure what previous error was... doesn't seem like SSO issue because of the vue nav logs.

Might consider taking the test folders out of codeQL analysis at some point? Lots of false alarms there

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-279

**Review by jujaga — APPROVED** [review]

**Pull request merged**
