### PR TITLE
Add Print Button

### PR DESCRIPTION
**Pull request by jujaga**
# Description

This PR adds a QoL Print button and some minor code cleanup and consolidation.

[SHOWCASE-1991](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1991)

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-194

**Review by loneil — COMMENTED** [review]
Code changes look good, will test some browsers tomorrow when dev.oidc is un-broken.

**Review by MichaelChung123 — COMMENTED** [review]
Looks good, will do testing as well and add a review.

**Review by MichaelChung123 — APPROVED** [review]
Tested, approved

**Review by loneil — APPROVED** [review]

**Pull request merged**
