### PR TITLE
Admin Form Users

### PR DESCRIPTION
**Pull request by MichaelChung123**
# Description
Adding user information to the form/admin page.

## Types of changes
Attached the backend to make a call to the admin/service layer to display user data on the frontend.

## Checklist

- [X] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [X] I have checked that unit tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-254

**Comment by TimCsaky** [comment]
i guess listing all forms (and user's roles/permissions) on the user details page.. isnt possible using existing api functions.
so showing all users (and their roles/permission) on a form details page is a good alternative.

**Review by loneil — APPROVED** [review]
Good stuff, looks good to me

**Review by jujaga — APPROVED** [review]
Please update the OpenAPI spec to also reflect the casing change on `/admin/formUsers`:
https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-254/api/v1/docs#operation/adminReadFormUsers
Will tentatively approve, assuming the above fix gets in.

**Pull request merged**
