### PR TITLE
Remove Team Member Functionality and UX Consistency Pass

### PR DESCRIPTION
**Pull request by jujaga**
# Description

This PR implements the ability for Team Management panel to remove users.
* Add form owner protection logic
* Button style consistency pass
* Page Title/Action button consistency pass
* Add missing tooltips
* Disable submitter column when not in team mode

[SHOWCASE-1728](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1728)
[SHOWCASE-1749](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1749)

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by bcgov-nr-csst** [comment]
SonarQube Analysis: https://sonarqube-wxpbtr-tools.pathfinder.gov.bc.ca/dashboard?id=common-hosted-form-service-pr-97

**Comment by TimCsaky** [comment]
image
this settings icon could be hidden while they are in 'add user' mode

**Comment by bcgov-nr-csst** [comment]
SonarQube Analysis: https://sonarqube-wxpbtr-tools.pathfinder.gov.bc.ca/dashboard?id=common-hosted-form-service-pr-97

**Review by loneil — APPROVED** [review]
Great stuff, looking good

**Pull request merged**
