### PR TITLE
bugfix_search_not_working_with_pagination

### PR DESCRIPTION
**Pull request by timisenco2015**
# Description
This PR is a fix for search functionality not working in both the SubmissionTable.vue and MySubmissionsTable.vue

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have run the npm script lint on the frontend and backend
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have approval from the product owner for the contribution in this pull request

### CODE REVIEW

**Comment by WalterMoar** [comment]
@timisenco2015 - I added you to "Walter's Form" in the PR environment. When I add `simpletextfield` to the submissions table and search for "aa" it doesn't find "AA". I think because it's not doing a case-insensitive search. However, it's also find a submission that does not contain "aa". I don't know why that is being selected.
image

**Comment by WalterMoar** [comment]
If I just type 'a' in the `Walter's Form` submissions, it switches to only 9 results on the page but still says `1-10 of 12`.
image

**Comment by WalterMoar** [comment]
If I switch `Walter's Form` to 5 results per page and then type `a` and then `backspace`, I see 10 results:
image

**Comment by WalterMoar** [comment]
In the Admin forms, a search that return no results shows this message:
image
But in the submissions it says that there are no submissions for the form:
image
I'd be worried that people would get confused by this. Would it be possible to put in a message that says nothing matches the search term?

**Comment by WalterMoar** [comment]
I think one of the problems is that it's matching on the columns that aren't being displayed:
image

**Comment by timisenco2015** [comment]
> I think one of the problems is that it's matching on the columns that aren't being displayed: image

I did not work on the admin side.

**Comment by timisenco2015** [comment]
> In the Admin forms, a search that return no results shows this message: image But in the submissions it says that there are no submissions for the form: image I'd be worried that people would get confused by this. Would it be possible to put in a message that says nothing matches the search term?

I did not work on the admin side.

**Comment by timisenco2015** [comment]
> @timisenco2015 - I added you to "Walter's Form" in the PR environment. When I add `simpletextfield` to the submissions table and search for "aa" it doesn't find "AA". I think because it's not doing a case-insensitive search. However, it's also finding a submission that does not contain "aa". I don't know why that is being selected. image

It is checking against submission id. e.g. this submission id '1bfc8a79-4bd7-4aa6-be31-af95c9b07ea4' has aa

**Comment by WalterMoar** [comment]
> > @timisenco2015 - I added you to "Walter's Form" in the PR environment. When I add `simpletextfield` to the submissions table and search for "aa" it doesn't find "AA". I think because it's not doing a case-insensitive search. However, it's also finding a submission that does not contain "aa". I don't know why that is being selected. image
> 
> It is checking against submission id. e.g. this submission id '1bfc8a79-4bd7-4aa6-be31-af95c9b07ea4' has aa

Ahh, I see. Would it be possible to only search the columns that are shown in the table?

**Comment by timisenco2015** [comment]
> I think one of the problems is that it's matching on the columns that aren't being displayed: image

The backend does not know what columns are displayed at the frontend. To able to search based on the columns displayed, we have to pass those columns to the backend, which might be complicated because we will be passing up to 20 columns or more to the backend

**Comment by WalterMoar** [comment]
In the form `Walter's Form`, if I do:
1. Go to submissions page
2. Search by Confirmation ID
3. Change to 5 rows per page
4. Search for `a`
5. Go to page 2 of the results

There are too many rows in the table:
image

Can you also write tests for the backend? (Skip frontend testing until we get to Vue 3). It seems that there are a lot of different cases that need to be handled, and we have to worry about accidentally breaking them in the future.

**Review by WalterMoar — APPROVED** [review]

**Pull request merged**
