### PR TITLE
Unable to select all versions for export 

### PR DESCRIPTION
**Pull request by timisenco2015**
# Description
Added “All” option to drop-down menu in submission export page

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have run the npm script lint on the frontend and backend
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have approval from the product owner for the contribution in this pull request

### CODE REVIEW

**Comment by WalterMoar** [comment]
When selecting "All" versions it isn't exporting the data if form fields change.

image

1. Published a new form with text field `simpletextfield`
2. Created a submission
3. Published a new version of the form, but renamed `simpletextfield` to `simpletextfield2`
4. Created a submission
5. Exported "All" versions

I don't know if it is possible for us to export "all" versions to a single file. The fields could be completely different between versions of the form.

**Comment by timisenco2015** [comment]
> When selecting "All" versions it isn't exporting the data if form fields change.
> 
> image
> 
> 1. Published a new form with text field `simpletextfield`
> 2. Created a submission
> 3. Published a new version of the form, but renamed `simpletextfield` to `simpletextfield2`
> 4. Created a submission
> 5. Exported "All" versions
> 
> I don't know if it is possible for us to export "all" versions to a single file. The fields could be completely different between versions of the form.

Good morning. I saw your comment, Walter. Yes, that was why we did not add the "All" initially, but since users can use the API directly by not specifying the form version number, it might not be a bad idea to add it to the front end. That is why I did make it "all" a default value

**Comment by timisenco2015** [comment]
> When selecting "All" versions it isn't exporting the data if form fields change.
> 
> image
> 
> 1. Published a new form with text field `simpletextfield`
> 2. Created a submission
> 3. Published a new version of the form, but renamed `simpletextfield` to `simpletextfield2`
> 4. Created a submission
> 5. Exported "All" versions
> 
> I don't know if it is possible for us to export "all" versions to a single file. The fields could be completely different between versions of the form.

Yes, that was why we did not add the "All" initially, but since users can use the API directly by not specifying the form version number, it might not be a bad idea to add it to the front end. That is why I did make it "all" a default value.

**Comment by WalterMoar** [comment]
> > When selecting "All" versions it isn't exporting the data if form fields change.
> > image
> > 
> > 1. Published a new form with text field `simpletextfield`
> > 2. Created a submission
> > 3. Published a new version of the form, but renamed `simpletextfield` to `simpletextfield2`
> > 4. Created a submission
> > 5. Exported "All" versions
> > 
> > I don't know if it is possible for us to export "all" versions to a single file. The fields could be completely different between versions of the form.
> 
> Yes, that was why we did not add the "All" initially, but since users can use the API directly by not specifying the form version number, it might not be a bad idea to add it to the front end. That is why I did make it "all" a default value.

Is there a way to include all fields from all versions? I tried another scenario:

1. Published a new form with text field `field1`
2. Created a submission
3. Published a new version of the form, adding `field2`
4. Created a submission
5. Exported "All" versions

image

It's only including `field`. So it looks like any new fields added to new versions of the form will never be exported.

I think we're going to get a lot of bug reports about missing fields from the exports.

**Pull request closed without merging**
