### PR TITLE
Update dependencies and vuetify deprecation errors

### PR DESCRIPTION
**Pull request by jujaga**
# Description

Routine NPM package updates

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by MichaelChung123 — APPROVED** [review]

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-236

**Review by TimCsaky — APPROVED** [review]

**Review by loneil — CHANGES_REQUESTED** [review]
Issue with the header color

image

**Comment by bcgov-nr-csst** [comment]
PR Deployed at: https://chefs-dev.apps.silver.devops.gov.bc.ca/pr-236

**Review by loneil — APPROVED** [review]
Did a quick regression test

**Pull request merged**
